require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/accounts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Account. As you add validations to Account, be sure to
  # adjust the attributes here as well.
  let!(:account) {create(:account)}
  let!(:account_attributes) {attributes_for(:account)}

  describe "GET /index" do
    context "when the account exists"  do
      before do
        get "/accounts/"
      end

      it "renders a successful response" do
        expect(response).to have_http_status(:success)
      end

      it "renders accounts number" do
        expect(response.body).to include(account.account_number)
      end

      it "renders account supplier name" do
        expect(response.body).to include(account.supplier.name.to_s)
      end
    end
  end

  describe "GET /show" do
    context "when the account exists"  do
      before do
        get "/accounts/", params: {id:account.id}
      end

      it "renders a successful response" do
        expect(response).to have_http_status(:success)
      end

      it "renders accounts number" do
        expect(response.body).to include(account.account_number)
      end

      it "renders account supplier name" do
        expect(response.body).to include(account.supplier.name.to_s)
      end
    end

    context "when the account doesn't exists" do
      let!(:account_error) {build(:account)}
      before do
        get "/accounts/", params: {id:account_error.id}
      end

      it "not renders account number" do
        expect(response.body).to_not include(account_error.account_number)
      end
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get "/accounts/new"
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    context "when the accounts exists"  do
      before do
        get "/accounts/#{account.id}/edit"
      end

      it "renders a successful response" do
        expect(response).to be_successful
      end

      it "renders account supplier name" do
        expect(response.body).to include(account.supplier.name)
      end
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      before do
        account_ = build(:account)
        post "/accounts/", params: { account: account_ }
      end

      it "creates a new accounts" do
        puts response.body
        expect(response).to have_http_status(:redirect)
      end

      it "redirects to the created accounts" do
        get "/accounts", params: { id: account.id }
        expect(response.body).to include("Account was successfully created.")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested account" do
        account = Account.create! valid_attributes
        patch account_url(account), params: { account: new_attributes }
        account.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the account" do
        account = Account.create! valid_attributes
        patch account_url(account), params: { account: new_attributes }
        account.reload
        expect(response).to redirect_to(account_url(account))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        account = Account.create! valid_attributes
        patch account_url(account), params: { account: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested account" do
      account = Account.create! valid_attributes
      expect {
        delete account_url(account)
      }.to change(Account, :count).by(-1)
    end

    it "redirects to the accounts list" do
      account = Account.create! valid_attributes
      delete account_url(account)
      expect(response).to redirect_to(accounts_url)
    end
  end
end
